workflows:
  android-workflow:
    name: Android Build

    scripts:
      - flutter pub get
      - flutter build apk --release --flavor prod
      - flutter build apk --release --flavor dev

    artifacts:
      - build/app/outputs/flutter-apk/app-prod-release.apk
      - build/app/outputs/flutter-apk/app-dev-release.apk
