workflows:
  android-ios-workflow:
    name: Android & iOS Build

    environment:
      flutter: stable
      xcode: latest

    scripts:
      - flutter pub get

      # Android builds
      - flutter build apk --release --flavor prod
      - flutter build apk --release --flavor dev

      # iOS build (no signing)
      - flutter build ios --release --no-codesign

    artifacts:
      # Android
      - build/app/outputs/flutter-apk/*.apk

      # iOS
      - build/ios/iphoneos/*.app
